import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex gap-2 justify-between px-4 bg-blue-700">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/about/"}>About</Link>
            </li>
            <li>
              <Link href={"/about/me"}>Me</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
