import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode;
}>) {
  const isAdmin = false;
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex gap-2 justify-between px-4 bg-blue-700">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/abouts"}>About</Link>
            </li>
          </ul>
        </nav>
        {children}
        {isAdmin && profile}
      </body>
    </html>
  );
}
